name: device_security_checker

description: A Flutter plugin for detecting common device security risks such as Developer Mode, USB Debugging, Emulator/Simulator, and more.

version: 1.1.1

homepage: https://github.com/vijayisonwork/device_security_checker
repository: https://github.com/vijayisonwork/device_security_checker
documentation: https://github.com/vijayisonwork/device_security_checker
issue_tracker: https://github.com/vijayisonwork/device_security_checker/issues

topics:
  - flutter
  - android
  - ios
  - security
  - device

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.vs_plugin.device_security_checker
        pluginClass: DeviceSecurityCheckerPlugin
      ios:
        pluginClass: DeviceSecurityCheckerPlugin