name: device_security_checker

description: A Flutter plugin for detecting common device security risks such as Developer Mode, USB Debugging, Emulator/Simulator, and more.

version: 1.1.3

homepage: https://github.com/vijayisonwork/device_security_checker
repository: https://github.com/vijayisonwork/device_security_checker
documentation: https://github.com/vijayisonwork/device_security_checker
issue_tracker: https://github.com/vijayisonwork/device_security_checker/issues

topics:
  - flutter
  - android
  - ios
  - security
  - device

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.vs_plugin.device_security_checker
        pluginClass: DeviceSecurityCheckerPlugin
      ios:
        pluginClass: DeviceSecurityCheckerPlugin

screenshots:
  - description: Developer Mode
    path: screenshots/developer_mode.jpeg

  - description: USB Debugging
    path: screenshots/usb_debugging.jpeg

  - description: Debugger Attached
    path: screenshots/debugger_attached.jpeg

  - description: Virtual Device
    path: screenshots/virtual_device.jpeg

  - description: Device Compromised
    path: screenshots/device_compromised.jpeg

  - description: Device Secure
    path: screenshots/device_secure.jpeg